---
title: "Data Processing README"
author: "Christian Opperman, Melanie Zheng, and Paul Choi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction

This document describes our group's philosophy and methodology behind the data cleaning, imputation, and feature generation/feature engineering for use in our Kaggle machine learning project for the NYC Data Science Academy.

Overall, we implemented the following pipeline for our data processing:

1. Import raw data
2. Remove outliers in training data
3. Impute data:
    + Impute pseudo-missing values
    + Impute true-missing values
    + Re-engineer categorical features as necessary
4. Add new feature variables
5. Dummify categorical feature variables
6. Remove unnecessary feature variables

One important quality of the data that it's important to reconcile is that there were many more feature variables with missing values in the test dataset than there were in the training dataset. As a result, our group decided on a data processing pipeline that took a function-forward approach, so that the end result would be a single function that would correctly process either the training or the test dataset. Therefore, the below detailed explanation puts forth our philosophy on first types of variables (pseudo-missing, true-missing, categorical, etc.) and then on specific variables, rather than on an individual dataset.

### Outliers in Training Data 
An examination of the distribution of our feature space revealed that there were two clear outliers in the relation between 'SalePrice' and 'GrLivArea' (a representation of the overall living area of the house). While the overall relationional trend between these two variables is positive and linear, there were two observations with a living area greater than 4000 square feet but a sale price less than $300,000, which had negative effects on the overall trend between the two variables.

Because there were only two observations out of the 1,460 observations in our training data, we judged it more efficient to remove those observations than to attempt to transform the 'GrLivArea' variable to reduce the outlier-induced skew.

### Data Imputation
#### Pseudo-Missing Values
There were a number of feature variables that contained missing values that did not, in fact, represent missing data. Instead of an incomplete observation, missing values in these features represented a lack of the element in question on the property. Our group termed those features with this quality "pseudo-missing."

The general philosophy for a given variable X (where X represents a housing feature such as a pool, a fireplace, etc.) was to impute missing values as "No X".

The fourteen feature variables with pseudo-missingness were: Alley, BsmtCond, BsmtQual, BsmtFinType1, Fence, Fireplace, GarageCond, GarageFinish, GarageQual, GarageType, GarageYrBlt, MasVnrType, MiscFeature, and PoolQC.

#### True-Missing Values
In addition to the feature variables with pseudo-missingness, there were five features where missing values indicated true missing data. Those variables were: Electrical, MasVnrArea, LotFrontage, BsmtExposure, and BsmtFinType2. Because many of our machine learning modesls are unable to handle missing data, it was necessary for us to impute the missing values for these feature variables given the data to which we did have access.

By and large, the variables were imputed using Mode imputation. When doing so, feature variables were grouped by other, relevant features (for example, MasVnrArea was grouped by Neighboorhood and YearBuilt) to provide a more accurate and granular imputation.

Additionally, a handful of variables related to garages and basements exhibited both pseudo-missingness and true missingness. Those variables were first processed to fill any pseudo-missingness. This was achieved by imputed rows that corresponded to missingness in  *all* features related to the relevant housing amenity (garage or basement) with the same methodolgy described in the pseudo-missingness section above; once that was taken care of, the remaining missing values were imputed using the appropriate mode imputation.

#### Categorical Variables
The distribution of a large number of categorical variables was such that many of the features were dominated by a single value, with the remaining values being more sparsely populated. Because this sparsity resulted in a lack of representative data, and in an attempt to reduce the feature space expansion resulting from the need to dummify categorical features, we consolidated those categorical variables to follow the general pattern of "Dominant Class(es), Other."

Feature variables engineered in this way were: Exterior1st, RoofMatl, RoofStyle, Condition1, LotShape, Functional, Electrical, Heating, Foundation, and SaleType.

Additionally, some categorical variables represented an ordinal ranking - for instance, there were numerous variables related to the quality or condition of some housing feature, which were represented by categorical strings (such as "Excellent," "Fair," etc.). Because quality and condition are inherently ranked, we converted these variables to ordinal variables, to reduce the need for dummification.

### New Feature Variables
To reduce the size of the feature space without losing important data, the following feature variables were combined to create new feature variables:

+ 1stFlrSF + 2ndFlrSF + TotalBsmtSF -> TotalSF
+ BsmtFullBath + FullBath -> TotalFullBath
+ BsmtHalfBath + HalfBath -> TotalHalfBath

Additionally, new categorical feature variables were created to indicate whether a given home had a garage (IsGarage) or a pool (IsPool).

### Dummifying Feature Variables
All categorical feature variables were dummified using One Hot Encoding for use in linear refgression-based machine learning models.

### Removed Feature Variables
Some feature variables were rendered unnecessary by the engineering above. Others were so highly correlated with other variables that inclduing them violated core assumptions of linear models, and yet others had too few observations to be statistically useful.

+ Target Variable: SalePrice
+ Dropped due to no useful information: Id
+ Dropped due to re-engineering: TotalBsmtSF, 1stFlrSF, 2ndFlrSF, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath
+ Dropped for correlation reasions: BsmtFinSF1, BsmtFinSF2, BsmtUnfSF, GrLivArea, GarageYrBlt, GarageCars
+ Dropped for lack of observations: LowQualFinSF, PoolArea